name: CI/CD - Flask App on AKS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: tonACR.azurecr.io
      IMAGE_NAME: flask-content-app
      CLUSTER_NAME: ton-cluster-aks
      RESOURCE_GROUP: ton-resource-group
      AKS_NAMESPACE: default

    steps:
    - name:  Checkout du code
      uses: actions/checkout@v3

    - name:  Connexion à Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Connexion à ACR
      run: az acr login --name ${{ env.ACR_NAME }}

    - name:  Build et Push de l'image Docker
      run: |
        docker build -t $ACR_NAME/$IMAGE_NAME:latest .
        docker push $ACR_NAME/$IMAGE_NAME:latest

    - name:  Connexion à AKS
      run: az aks get-credentials --name $CLUSTER_NAME --resource-group $RESOURCE_GROUP --overwrite-existing

    - name:  Déploiement sur AKS
      run: |
        kubectl apply -f k8s/
